language: node_js
node_js:
- "6"
- "5"
- "5.1"
- "4"
- "4.4"
- "4.3"
- "4.2"
- "4.1"
- "4.0"
- "0.12"
- "0.11"
- "0.10"
- "iojs"
os:
- linux
- osx
after_success:
- ./node_modules/codecov/bin/codecov -e TRAVIS_NODE_VERSION
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js --verbose
- ./node_modules/codeclimate-test-reporter/bin/codeclimate.js < ./coverage/lcov.info
branches:
    only: # whitelist
    - master
    - develop
    - /^(bugfix|feature)\/#\d+.*$/
    - /^hotfix\/.*$/
